#!/bin/bash

cd lab0

chmod a-rwx,ug+r hariyama5
chmod a-rwx,u+wx,go+x hippowdon0
chmod 440 hippowdon0/nidorina/timburr
chmod 764 hippowdon0/mothim
chmod 576 hippowdon0/mothim/nidorina
chmod 570 hippowdon0/mothim/pikachu
chmod 737 hippowdon0/mothim/linoone
chmod 400 hippowdon0/mothim/nidoranM
chmod a-rwx,ug+r hippowdon0/mothim/dusclops
chmod 537 hippowdon0/nidorina
chmod u=rwx,g=rw,o=r hippowdon0/nidorina/bastiodon
chmod 440 hippowdon0/nidorina/timburr
chmod 570 hippowdon0/gothitelle
chmod 400 hippowdon0/gothitelle/doduo
chmod 044 hippowdon0/gothitelle/seadra
chmod 044 hippowdon0/gothitelle/shelgon
chmod 512 hippowdon0/gothitelle/spearow
chmod uo=wx,g=rwx hippowdon0/gothitelle/flareon
chmod 400 hippowdon0/gothitelle/grotle
chmod 571 hippowdon0/gothitelle/shroomish
chmod 440 hippowdon0/koffing
chmod 062 hippowdon0/pansage
chmod 044 ponyta5
chmod 711 shroomish2
chmod 044 shroomish2/hitmonchan
chmod 550 shroomish2/ninetales
chmod 355 shroomish2/ninetales/clefable
chmod 755 shroomish2/ninetales/raichu
chmod u=rx,g=x,o=w shroomish2/emboar
chmod 677 shroomish2/emboar/snivy
chmod 400 shroomish2/emboar/grumpig
chmod 666 shroomish2/tangrowth
chmod 315 shroomish2/nincada
chmod 004 shroomish2/nincada/grovyle
chmod 046 shroomish2/nincada/medicham
chmod 004 shroomish2/nincada/chinchou
chmod a-rwx,u=r shroomish2/nincada/oddish
chmod u-rwx,go=r shroomish2/nincada/omanyte
chmod g-rwx,uo=r shroomish2/nincada/crawdaunt
chmod u=rx,g=rwx,o=rw shroomish2/nincada/porygon
chmod 752 slakoth8
chmod 700 slakoth8/scraggy
chmod u=rx,go=rwx slakoth8/scraggy/sandile
chmod a-rwx,o=r slakoth8/scraggy/reuniclus
chmod 335 slakoth8/blitzle
chmod 511 slakoth8/blitzle/infernape
chmod 062 slakoth8/blitzle/kabuto
chmod 400 slakoth8/blitzle/crawdaunt
chmod 513 slakoth8/drilbur
chmod 700 slakoth8/drilbur/staravia
chmod a-rwx,u=r slakoth8/drilbur/weavile
chmod 570 slakoth8/drilbur/spearow
chmod 004 slakoth8/drilbur/alakazam
chmod 440 slakoth8/drilbur/piplup
chmod 375 slakoth8/drilbur/yanmega
chmod a-rwx,g=r,o=rw wynaut9
